apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
type: Opaque
stringData:
  mysql-root-password: root
  jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  mail-host: smtp.gmail.com
  mail-username: your-email@gmail.com
  mail-password: your-app-password
